### ISSUE TITLE
MELD dataset

### ISSUE THREAD

**Issue by JiNan0831** [zerohd4869/MM-DFN#10]
I found that the MELD dataset you use is 5-classified, and there is no comparison of how you process the two types of data in feature extraction, or how you use to process the two types of data.

**Comment by hongkunzhao** [comment]
I'm running code like torch-scatter torchvision torch_sparse packages can't find modules, how do you run it?

**Comment by zerohd4869** [comment]
> I found that the MELD dataset you use is 5-classified, and there is no comparison of how you process the two types of data in feature extraction, or how you use to process the two types of data.

As mentioned in our paper, this work used the default 7 emotion categories in the MELD dataset, not the 5 you mentioned. Thank you.
