### ISSUE TITLE
About the processed data

### ISSUE THREAD

**Issue by wuxy07** [zerohd4869/MM-DFN#13]
I am currently examining the processed dataset you have shared in your code. In MELD_features_raw1.pkl, I have noted that the second section pertains to speaker information. Each identifier corresponds to a speech segment, and for each segment, there are as many vectors as there are sentences. However, I observed that each vector has a dimension of 9. Could you kindly clarify if the value 9 holds any particular significance? Thank you very much for your assistance.

**Comment by zerohd4869** [comment]
> I am currently examining the processed dataset you have shared in your code. In MELD_features_raw1.pkl, I have noted that the second section pertains to speaker information. Each identifier corresponds to a speech segment, and for each segment, there are as many vectors as there are sentences. However, I observed that each vector has a dimension of 9. Could you kindly clarify if the value 9 holds any particular significance? Thank you very much for your assistance.

In MELD_features_raw1.pkl, the vector information with a dimension of 9 means the mapping for the speaker indices in the current session. The speakers in different sessions are generally not the same, but the maximum number of speakers in each session is <= 9.

In this work, our method only utilizes the sequence information of speakers, without strictly distinguishing which speaker each utterance belongs to. In the processed MELD features, there is no fixed speaker mapping, and different sessions usually have different mappings.

I hope this can explain the meaning of the speaker indices.

**Comment by wuxy07** [comment]
> > 我目前正在检查您在代码中共享的已处理数据集。在 MELD_features_raw1.pkl 中，我注意到第二部分与说话人信息有关。每个标识符对应于一个语音段，对于每个段，向量与句子的数量一样多。但是，我观察到每个向量的维度为 9。您能否澄清一下值 9 是否具有任何特殊意义？非常感谢您的帮助。
> 
> 在 MELD_features_raw1.pkl 中，维度为 9 的向量信息表示当前会话中说话人索引的映射。不同会议的发言者一般不相同，但每场会议的最大发言者人数为 <= 9。
> 
> 在这项工作中，我们的方法只利用了说话人的序列信息，没有严格区分每个话语属于哪个说话人。在处理后的 MELD 功能中，没有固定的说话人映射，不同的会话通常具有不同的映射。
> 
> 我希望这可以解释说话人索引的含义。

Thank you very much for your detailed explanation! It has greatly helped me understand the significance of the speaker indices in MELD_features_raw1.pkl. Your assistance is greatly appreciated. Thanks again!

**Comment by wuxy07** [comment]
> > I am currently examining the processed dataset you have shared in your code. In MELD_features_raw1.pkl, I have noted that the second section pertains to speaker information. Each identifier corresponds to a speech segment, and for each segment, there are as many vectors as there are sentences. However, I observed that each vector has a dimension of 9. Could you kindly clarify if the value 9 holds any particular significance? Thank you very much for your assistance.
> 
> In MELD_features_raw1.pkl, the vector information with a dimension of 9 means the mapping for the speaker indices in the current session. The speakers in different sessions are generally not the same, but the maximum number of speakers in each session is <= 9.
> 
> In this work, our method only utilizes the sequence information of speakers, without strictly distinguishing which speaker each utterance belongs to. In the processed MELD features, there is no fixed speaker mapping, and different sessions usually have different mappings.
> 
> I hope this can explain the meaning of the speaker indices.

Thank you very much for your detailed explanation! It has greatly helped me understand the significance of the speaker indices in MELD_features_raw1.pkl. Your assistance is greatly appreciated. Thanks again!
