### ISSUE TITLE
Couldn't change the training dataset from IEMOCAP to MELD

### ISSUE THREAD

**Issue by jellyfishovo** [zerohd4869/MM-DFN#6]
Greetings!
i try to train with MELD dataset and  change the parameter in :
parser.add_argument('--dataset', default='IEMOCAP', help='dataset to train and test')

and change the IEMOCAP to MELD ,while it reports:
ValueError: not enough values to unpack (expected 10, got 9)

what else can i change
Thanks!!!!

**Comment by zerohd4869** [comment]
> Greetings! i try to train with MELD dataset and change the parameter in : parser.add_argument('--dataset', default='IEMOCAP', help='dataset to train and test')
> 
> and change the IEMOCAP to MELD ,while it reports: ValueError: not enough values to unpack (expected 10, got 9)
> 
> what else can i change Thanks!!!!

Thank you for your question. Based on your error report, it seems that you have modified the --dataset parameter in the *.py file to "MELD" and encountered an error when running the *.py file. It's possible that you may have forgotten to modify important path settings, especially the '--data_dir' option that specifies the dataset directory.

I suggest that you ensure that you have correctly modified the relevant paths and parameters before running the *.py file. Additionally, I recommend that you use the provided *.sh script for running the code, as the latest version of the script includes recommended hyperparameter ranges and facilitates reproducibility across different environments.

If you encounter any further issues, please don't hesitate to ask.

**Comment by jellyfishovo** [comment]
Thanks! 
i forgrt to change the dataset dir and after that the model works on MELD
